sudo: required
language: generic
services:
    - docker

before_install:
    - docker build -f ./client/Dockerfile.dev -t zdend/docker-5 ./client

script:
    - docker run -e CI=true zdend/docker-5 npm run test

after_success:
    - docker build -t zdend/docker-5-client ./client
    - docker build -t zdend/docker-5-ngnix ./nginx
    - docker build -t zdend/docker-5-server ./server
    - docker build -t zdend/docker-5-worker ./worker
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    - docker push zdend/docker-5-client
    - docker push zdend/docker-5-ngnix
    - docker push zdend/docker-5-server
    - docker push zdend/docker-5-worker

deploy:
    provider: elasticbeanstalk
    region: "ap-southeast-2"
    app: "docker-5"
    env: "Docker5-env"
    bucket_name: "elasticbeanstalk-ap-southeast-2-254591791041"
    bucket_path: "docker-5"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY