sudo: required
language: generic
services:
    - docker

# before_install:
#     - docker build -f Dockerfile.dev -t zdend/docker-5 .

# script:
#     - docker run -e CI=true zdend/docker-5 npm run test

# deploy:
#     provider: elasticbeanstalk
#     region: "ap-southeast-2"
#     app: "docker-4"
#     env: "Docker4-env"
#     bucket_name: "elasticbeanstalk-ap-southeast-2-254591791041"
#     bucket_path: "docker-4"
#     on:
#         branch: master
#     access_key_id: $AWS_ACCESS_KEY
#     secret_access_key: $AWS_SECRET_KEY